#!/bin/bash

_other_installs () {
   if [[ $OTHER_INSTALLS != "None" ]]
   then
    apt install $OTHER_INSTALLS -y
   fi
   }
_externals () {
   if [[ $OTHER_CMD != "None" ]]
   then
      $OTHER_CMD
   fi
   }
    
apt update && apt upgrade -y
apt install git -y
_other_installs
pip3 install -U pip
#git clone $REPO_URL Github_Repo
#cd Github_Repo
apt install -y unzip
unzip "SBD.zip" -d "/app/"
mv "/app/SBDriveBot-9/sample_config.py" "/app/SBDriveBot-9/config.py"
cp -r "/app/SBDriveBot-9/plugins" "plugins"
cp -r "/app/SBDriveBot-9/helper_funcs" "helper_funcs"
cp -r "/app/SBDriveBot-9/mycreds.txt" "mycreds.txt"
cp -r "/app/SBDriveBot-9/client_secrets.json" "client_secrets.json"
cp -r "/app/SBDriveBot-9/settings.yaml" "settings.yaml"
pip3 install -U -r "/app/SBDriveBot-9/requirements.txt"
_externals
python "/app/SBDriveBot-9/$PYTHON_FILE"
